-- Create connection_status table for integration testing
CREATE TABLE public.connection_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status SMALLINT DEFAULT 0 CHECK (status IN (0, 1)),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.connection_status ENABLE ROW LEVEL SECURITY;

-- Note: No policies needed for now since we use the service_role key in tests.
