import dotenv from "dotenv";
import fs from "fs";
import path from "path";

const keysPath = path.join(process.cwd(), ".supabase-keys.json");

// 1. Always try to load from .supabase-keys.json first (generated by npm pretest)
if (fs.existsSync(keysPath)) {
  try {
    const keys = JSON.parse(fs.readFileSync(keysPath, "utf8"));

    // Map the Supabase CLI keys to the environment variables our app expects
    if (keys.API_URL) {
      process.env.EXPO_PUBLIC_SUPABASE_URL = keys.API_URL;
    }

    // For tests, we use the SERVICE_ROLE_KEY so we can bypass RLS 
    // and actually test the database integration.
    if (keys.SERVICE_ROLE_KEY) {
      process.env.EXPO_PUBLIC_SUPABASE_KEY = keys.SERVICE_ROLE_KEY;
    }
  } catch (e) {
    console.error("Error parsing .supabase-keys.json:", e);
  }
}

// 2. Fallback to .env.test if variables aren't set
if (!process.env.EXPO_PUBLIC_SUPABASE_URL && fs.existsSync(".env.test")) {
  dotenv.config({ path: ".env.test" });
}

// 3. Final fallback to .env if still not set
if (!process.env.EXPO_PUBLIC_SUPABASE_URL && fs.existsSync(".env")) {
  dotenv.config({ path: ".env" });
}
